### ISSUE TITLE
pulldown_credits rewrite

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-deinterlace#20] opened 2023-04-21 19:01 UTC
Currently, `pulldown_credits` will deinterlace the entire clip when trying to pull down just 24/30 fps content. It should instead do the following:

- [ ] IVTC the clip, ideally allowing for a pre-IVTC'd clip to be passed somehow (as the pattern can change, and we want to avoid having the user manually selecting patterns if we can help it to ensure the decimations stay correct)
- [ ] Allow the user to pass a custom deinterlacing algo. Maybe use Bob by default (for speed + checking the clip purposes) and throw a warning if no custom deinterlacer is passed?
- [ ] Really, this should be something you can do in wobbly. It'd make more sense if were allowed to pick a range to apply this function in wobbly so we can do realtime checking.

**Comment by Setsugennoao** [comment] 2023-04-21 21:24
Use wobbly

**Comment by Setsugennoao** [comment] 2023-05-04 22:01
Dupe of https://github.com/Irrational-Encoding-Wizardry/vs-deinterlace/issues/16

**Closed by Setsugennoao** 2023-05-04 22:01 UTC
